# Generated by Django 4.2.5 on 2023-11-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "YoloObjectDetectionAPI",
            "0004_rename_detection_result_imageupload_detected_result",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="imageupload",
            name="model_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
